[project]
name = "nslps"
version = "0.1.0"
description = ""
authors = [
    { name = "eggunof", email = "eggunof@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openrouter (>=0.0.19,<0.0.20)",
    "dotenv (>=0.9.9,<0.10.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.4.0"
mypy = "^1.18.2"
pylint = "^4.0.3"
black = "^25.11.0"
isort = "^7.0.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^9.0.1"

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
include_trailing_comma = true
combine_as_imports = true
remove_redundant_aliases = true
